---
title: "STATS 101C -- Kaggle Project svm model"
author: "Group 5 Lec 1"
date: "`r format(Sys.Date(), '%D')`"
output:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: yes
    code_folding: show
  pdf_document:
    toc: yes
    toc_depth: '4'
---

## Packages
```{r packs, include = FALSE}

library(ggfortify)

library(ggplot2)

library(GGally)

library(gridExtra)

library(class)

library(ISLR)

library(MASS)

library(e1071)

library(crossval)

library(boot)

library(bootstrap)

library(resample)

library(Rfast)

library(caret)

library(glmnet)

library(mice)

library(dplyr)

library(pls)

library(randomForest)

library(e1071)

```

## Uploading data
```{r}

setwd("C://Users//ashis//OneDrive//Desktop//STATS_101C//Kaggle_Project//rmna")

traindata <- read.csv("compdtr.csv")

traindata[, 21] <- as.factor(traindata[, 21])
traindata[, 22] <- as.factor(traindata[, 22])
traindata[, 23] <- as.factor(traindata[, 23])
traindata[, 24] <- as.factor(traindata[, 24])
traindata[, 25] <- as.factor(traindata[, 25])
traindata[, 26] <- as.factor(traindata[, 26])
traindata[, 27] <- as.factor(traindata[, 27])

testdata <- read.csv("compdts.csv")

testdata[, 21] <- as.factor(testdata[, 21])
testdata[, 22] <- as.factor(testdata[, 22])
testdata[, 23] <- as.factor(testdata[, 23])
testdata[, 24] <- as.factor(testdata[, 24])
testdata[, 25] <- as.factor(testdata[, 25])
testdata[, 26] <- as.factor(testdata[, 26])

```


## svm model
```{r}

svm_model <-  svm(Alcoholic.Status ~ ., data = traindata, kernel = "radial",
                  cost = 5)

```

```{r}

pred <- predict(svm_model, newdata = testdata, type = "class")

write.csv(data.frame("ID"=c(1:30000), "Alcoholic.Status" = pred), 
          row.names = FALSE, 
          "C://Users//ashis//OneDrive//Desktop//STATS_101C//Kaggle_Project//svm_attempt//radialsvmpred2solution.csv")

```




